apiVersion: v1
kind: Service
metadata:
  name: kafdrop-loadbalancer
  namespace: trgs
spec:
  type: NodePort
  selector:
    app: trgs-kafdrop
  type: LoadBalancer
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
  externalIPs:
  - 192.168.58.2 

