apiVersion: v1
kind: Pod
metadata:
  name: trgs-kafdrop
  namespace: trgs
  labels:
    app: trgs-kafdrop
spec:
  containers:
  - name: trgs-kafdrop
    image: obsidiandynamics/kafdrop:latest
    ports:
    - containerPort: 9000
    env:
    - name: KAFKA_BROKERCONNECT
      value: "trgs-kafka:9092"
    - name: JVM_OPTS
      value: "-Xms16m -Xmx48m -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
