apiVersion: v1
kind: Pod
metadata:
  name: trgs-kafka
  namespace: trgs
  labels:
    app: trgs-kafka
spec:
  containers:
  - name: trgs-kafka-pod
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
    - containerPort: 9092
      containerPort: 9094
    env:
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "INSIDE://:9092,OUTSIDE://192.168.58.2:9094"
    - name: KAFKA_LISTENERS
      value: "INSIDE://:9092,OUTSIDE://:9094"
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: "INSIDE"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "trgs-zookeeper-service:2181"
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"
