apiVersion: v1
kind: Service
metadata:
  name: trgs-kafka
  namespace: trgs
spec:
  type: NodePort
  selector:
    app: trgs-kafka
  type: LoadBalancer
  ports:
  - name: http
    port: 9091
    targetPort: 9091
    protocol: TCP
  externalIPs:
  - 192.168.58.2 
