apiVersion: v1
kind: Service
metadata:
  name: trgs-kafka
  namespace: trgs
spec:
  type: NodePort
  selector:
    app: trgs-kafka
  ports:
  - name: internal
    port: 9092
    targetPort: 9092
    nodePort: 30092
  - name: external
    port: 9094
    targetPort: 9094
    nodePort: 30094
  externalIPs:
  - 192.168.58.2 

