apiVersion: v1
kind: Service
metadata:
  name: trgs-zookeeper-service
  namespace: trgs
spec:
  selector:
    app: trgs-zookeeper
  ports:
  - name: client-port
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: follower-port
    port: 2888
    targetPort: 2888
    protocol: TCP
  - name: election-port
    port: 3888
    targetPort: 3888
    protocol: TCP
  type: LoadBalancer
  externalIPs:
  - 192.168.58.2 
